package vn.eztek.springboot3starter.shared.redis;


public enum MessageEventType {
  DELETE_ACCOUNT,
  DELETE_PROJECT,
  DELETE_FILE,
  DELETE_FOLDER,
  SOCKET,
  RESTORE_PROJECT,
  RESTORE_ACCOUNT,
  SEND_EMAIL,
  SEND_EMULATOR,
  VERIFY_ACCOUNT,
  FINISH_VERIFY_ACCOUNT,
  NOTIFICATION_SOCKET,

}
