package vn.eztek.springboot3starter.domain.privilege.entity;

public enum PrivilegeName {
  CREATE_USER,
  UPDATE_USER,
  VIEW_USER,
  DELETE_USER,
  CREATE_PROJECT,
  VIEW_PROJECT,
  VIEW_MY_PROJECT,
  UPDATE_PROJECT,
  DELETE_PROJECT,
  UPDATE_PROFILE,
  VIEW_PROFILE,
  CREATE_INVITATION,
  VIEW_INVITATION,
  VIEW_MY_INVITATION,
  UPDATE_INVITATION,
  DELETE_INVITATION,
  CREATE_TASK,
  VIEW_TASK,
  UPDATE_TASK,
  DELETE_TASK,

}
