package vn.eztek.springboot3starter.shared.socket;


public enum SocketResponseType {
  TASK_ASSIGNED,
  PROJECT_INVITED,
  TASK_DELETED,
  COMMENT_ADDED,
  COMMENT_UPDATED,
  COMMENT_DELETED,
  COMMENT_REPLIED,
  TASK_UPDATED,
  ATTACHMENT_ADDED,
  ATTACHMENT_DELETED,
  TASK_UNASSIGNED,
  STAGE_UPDATED,
  TASK_POSITION_UPDATED,
  TASK_ADDED,
  ATTACHMENT_UPDATED,
  CHECK_LIST_ADDED,
  CHECK_LIST_UPDATED,
  CHECK_LIST_DELETED,
  CHECK_LIST_ITEM_ADDED,
  CHECK_LIST_ITEM_UPDATED,
  CHECK_LIST_ITEM_DELETED,
  CHECK_LIST_ITEM_ASSIGNED,
  CHECK_LIST_ITEM_UNASSIGNED,
  CHECK_LIST_ITEM_DUE_DATE_UPDATED,
  CHECK_LIST_ITEM_STATUS_UPDATED,
  LABEL_ADDED,
  LABEL_UPDATED,
  LABEL_DELETED,
  TASK_LABEL_ADDED,
  TASK_LABEL_REMOVED,
  LABEL_COLOR_REMOVED

}
